// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupPretypeMsg.proto

package com.im.group;
import com.google.protobuf.InvalidProtocolBufferException;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupPretypeMsg.proto
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupPretypeMsg.proto


final class GroupPretypeMsgProtobuf {
private GroupPretypeMsgProtobuf() {}
public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
}

public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
  registerAllExtensions(
          (com.google.protobuf.ExtensionRegistryLite) registry);
}
public interface SentDistributionMessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.im.secure.SentDistributionMessage)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>int64 userId = 2;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int32 identityKeyId = 3;</code>
   * @return The identityKeyId.
   */
  int getIdentityKeyId();

  /**
   * <code>int32 signedPreKeyId = 4;</code>
   * @return The signedPreKeyId.
   */
  int getSignedPreKeyId();

  /**
   * <code>bytes oneMsg = 5;</code>
   * @return The oneMsg.
   */
  com.google.protobuf.ByteString getOneMsg();
}
/**
 * Protobuf type {@code com.im.secure.SentDistributionMessage}
 */
public  static final class SentDistributionMessage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.im.secure.SentDistributionMessage)
        SentDistributionMessageOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use SentDistributionMessage.newBuilder() to construct.
  private SentDistributionMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SentDistributionMessage() {
    oneMsg_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
          UnusedPrivateParameter unused) {
    return new SentDistributionMessage();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SentDistributionMessage(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 16: {

            userId_ = input.readInt64();
            break;
          }
          case 24: {

            identityKeyId_ = input.readInt32();
            break;
          }
          case 32: {

            signedPreKeyId_ = input.readInt32();
            break;
          }
          case 42: {

            oneMsg_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return GroupPretypeMsgProtobuf.internal_static_com_im_secure_SentDistributionMessage_descriptor;
  }

  @Override
  protected FieldAccessorTable
  internalGetFieldAccessorTable() {
    return GroupPretypeMsgProtobuf.internal_static_com_im_secure_SentDistributionMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    GroupPretypeMsgProtobuf.SentDistributionMessage.class, GroupPretypeMsgProtobuf.SentDistributionMessage.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  public int getVersion() {
    return version_;
  }

  public static final int USERID_FIELD_NUMBER = 2;
  private long userId_;
  /**
   * <code>int64 userId = 2;</code>
   * @return The userId.
   */
  public long getUserId() {
    return userId_;
  }

  public static final int IDENTITYKEYID_FIELD_NUMBER = 3;
  private int identityKeyId_;
  /**
   * <code>int32 identityKeyId = 3;</code>
   * @return The identityKeyId.
   */
  public int getIdentityKeyId() {
    return identityKeyId_;
  }

  public static final int SIGNEDPREKEYID_FIELD_NUMBER = 4;
  private int signedPreKeyId_;
  /**
   * <code>int32 signedPreKeyId = 4;</code>
   * @return The signedPreKeyId.
   */
  public int getSignedPreKeyId() {
    return signedPreKeyId_;
  }

  public static final int ONEMSG_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString oneMsg_;
  /**
   * <code>bytes oneMsg = 5;</code>
   * @return The oneMsg.
   */
  public com.google.protobuf.ByteString getOneMsg() {
    return oneMsg_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (userId_ != 0L) {
      output.writeInt64(2, userId_);
    }
    if (identityKeyId_ != 0) {
      output.writeInt32(3, identityKeyId_);
    }
    if (signedPreKeyId_ != 0) {
      output.writeInt32(4, signedPreKeyId_);
    }
    if (!oneMsg_.isEmpty()) {
      output.writeBytes(5, oneMsg_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(1, version_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt64Size(2, userId_);
    }
    if (identityKeyId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(3, identityKeyId_);
    }
    if (signedPreKeyId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(4, signedPreKeyId_);
    }
    if (!oneMsg_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(5, oneMsg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof GroupPretypeMsgProtobuf.SentDistributionMessage)) {
      return super.equals(obj);
    }
    GroupPretypeMsgProtobuf.SentDistributionMessage other = (GroupPretypeMsgProtobuf.SentDistributionMessage) obj;

    if (getVersion()
            != other.getVersion()) return false;
    if (getUserId()
            != other.getUserId()) return false;
    if (getIdentityKeyId()
            != other.getIdentityKeyId()) return false;
    if (getSignedPreKeyId()
            != other.getSignedPreKeyId()) return false;
    if (!getOneMsg()
            .equals(other.getOneMsg())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUserId());
    hash = (37 * hash) + IDENTITYKEYID_FIELD_NUMBER;
    hash = (53 * hash) + getIdentityKeyId();
    hash = (37 * hash) + SIGNEDPREKEYID_FIELD_NUMBER;
    hash = (53 * hash) + getSignedPreKeyId();
    hash = (37 * hash) + ONEMSG_FIELD_NUMBER;
    hash = (53 * hash) + getOneMsg().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GroupPretypeMsgProtobuf.SentDistributionMessage parseFrom(
          java.nio.ByteBuffer data)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GroupPretypeMsgProtobuf.SentDistributionMessage parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.SentDistributionMessage parseFrom(
          com.google.protobuf.ByteString data)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GroupPretypeMsgProtobuf.SentDistributionMessage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.SentDistributionMessage parseFrom(byte[] data)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GroupPretypeMsgProtobuf.SentDistributionMessage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.SentDistributionMessage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }
  public static GroupPretypeMsgProtobuf.SentDistributionMessage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.SentDistributionMessage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }
  public static GroupPretypeMsgProtobuf.SentDistributionMessage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.SentDistributionMessage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }
  public static GroupPretypeMsgProtobuf.SentDistributionMessage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GroupPretypeMsgProtobuf.SentDistributionMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
          BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.im.secure.SentDistributionMessage}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.im.secure.SentDistributionMessage)
          GroupPretypeMsgProtobuf.SentDistributionMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return GroupPretypeMsgProtobuf.internal_static_com_im_secure_SentDistributionMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return GroupPretypeMsgProtobuf.internal_static_com_im_secure_SentDistributionMessage_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      GroupPretypeMsgProtobuf.SentDistributionMessage.class, GroupPretypeMsgProtobuf.SentDistributionMessage.Builder.class);
    }

    // Construct using com.im.secure.GroupPretypeMsgProtobuf.SentDistributionMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      userId_ = 0L;

      identityKeyId_ = 0;

      signedPreKeyId_ = 0;

      oneMsg_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return GroupPretypeMsgProtobuf.internal_static_com_im_secure_SentDistributionMessage_descriptor;
    }

    @Override
    public GroupPretypeMsgProtobuf.SentDistributionMessage getDefaultInstanceForType() {
      return GroupPretypeMsgProtobuf.SentDistributionMessage.getDefaultInstance();
    }

    @Override
    public GroupPretypeMsgProtobuf.SentDistributionMessage build() {
      GroupPretypeMsgProtobuf.SentDistributionMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GroupPretypeMsgProtobuf.SentDistributionMessage buildPartial() {
      GroupPretypeMsgProtobuf.SentDistributionMessage result = new GroupPretypeMsgProtobuf.SentDistributionMessage(this);
      result.version_ = version_;
      result.userId_ = userId_;
      result.identityKeyId_ = identityKeyId_;
      result.signedPreKeyId_ = signedPreKeyId_;
      result.oneMsg_ = oneMsg_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GroupPretypeMsgProtobuf.SentDistributionMessage) {
        return mergeFrom((GroupPretypeMsgProtobuf.SentDistributionMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GroupPretypeMsgProtobuf.SentDistributionMessage other) {
      if (other == GroupPretypeMsgProtobuf.SentDistributionMessage.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.getIdentityKeyId() != 0) {
        setIdentityKeyId(other.getIdentityKeyId());
      }
      if (other.getSignedPreKeyId() != 0) {
        setSignedPreKeyId(other.getSignedPreKeyId());
      }
      if (other.getOneMsg() != com.google.protobuf.ByteString.EMPTY) {
        setOneMsg(other.getOneMsg());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      GroupPretypeMsgProtobuf.SentDistributionMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (InvalidProtocolBufferException e) {
        parsedMessage = (GroupPretypeMsgProtobuf.SentDistributionMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {

      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {

      version_ = 0;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <code>int64 userId = 2;</code>
     * @return The userId.
     */
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 userId = 2;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 userId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {

      userId_ = 0L;
      onChanged();
      return this;
    }

    private int identityKeyId_ ;
    /**
     * <code>int32 identityKeyId = 3;</code>
     * @return The identityKeyId.
     */
    public int getIdentityKeyId() {
      return identityKeyId_;
    }
    /**
     * <code>int32 identityKeyId = 3;</code>
     * @param value The identityKeyId to set.
     * @return This builder for chaining.
     */
    public Builder setIdentityKeyId(int value) {

      identityKeyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 identityKeyId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentityKeyId() {

      identityKeyId_ = 0;
      onChanged();
      return this;
    }

    private int signedPreKeyId_ ;
    /**
     * <code>int32 signedPreKeyId = 4;</code>
     * @return The signedPreKeyId.
     */
    public int getSignedPreKeyId() {
      return signedPreKeyId_;
    }
    /**
     * <code>int32 signedPreKeyId = 4;</code>
     * @param value The signedPreKeyId to set.
     * @return This builder for chaining.
     */
    public Builder setSignedPreKeyId(int value) {

      signedPreKeyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 signedPreKeyId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignedPreKeyId() {

      signedPreKeyId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString oneMsg_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes oneMsg = 5;</code>
     * @return The oneMsg.
     */
    public com.google.protobuf.ByteString getOneMsg() {
      return oneMsg_;
    }
    /**
     * <code>bytes oneMsg = 5;</code>
     * @param value The oneMsg to set.
     * @return This builder for chaining.
     */
    public Builder setOneMsg(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }

      oneMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes oneMsg = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOneMsg() {

      oneMsg_ = getDefaultInstance().getOneMsg();
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.im.secure.SentDistributionMessage)
  }

  // @@protoc_insertion_point(class_scope:com.im.secure.SentDistributionMessage)
  private static final GroupPretypeMsgProtobuf.SentDistributionMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GroupPretypeMsgProtobuf.SentDistributionMessage();
  }

  public static GroupPretypeMsgProtobuf.SentDistributionMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SentDistributionMessage>
          PARSER = new com.google.protobuf.AbstractParser<SentDistributionMessage>() {
    @Override
    public SentDistributionMessage parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
      return new SentDistributionMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SentDistributionMessage> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SentDistributionMessage> getParserForType() {
    return PARSER;
  }

  @Override
  public GroupPretypeMsgProtobuf.SentDistributionMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

public interface SendMsgStateReqOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.im.secure.SendMsgStateReq)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>int32 registrationId = 2;</code>
   * @return The registrationId.
   */
  int getRegistrationId();

  /**
   * <code>int32 preKeyId = 3;</code>
   * @return The preKeyId.
   */
  int getPreKeyId();

  /**
   * <code>int32 signedPreKeyId = 4;</code>
   * @return The signedPreKeyId.
   */
  int getSignedPreKeyId();

  /**
   * <code>bytes baseKey = 5;</code>
   * @return The baseKey.
   */
  com.google.protobuf.ByteString getBaseKey();

  /**
   * <code>bytes identityKey = 6;</code>
   * @return The identityKey.
   */
  com.google.protobuf.ByteString getIdentityKey();

  /**
   * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
   */
  java.util.List<GroupPretypeMsgProtobuf.SentDistributionMessage>
  getMessageList();
  /**
   * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
   */
  GroupPretypeMsgProtobuf.SentDistributionMessage getMessage(int index);
  /**
   * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
   */
  int getMessageCount();
  /**
   * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
   */
  java.util.List<? extends GroupPretypeMsgProtobuf.SentDistributionMessageOrBuilder>
  getMessageOrBuilderList();
  /**
   * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
   */
  GroupPretypeMsgProtobuf.SentDistributionMessageOrBuilder getMessageOrBuilder(
          int index);
}
/**
 * Protobuf type {@code com.im.secure.SendMsgStateReq}
 */
public  static final class SendMsgStateReq extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.im.secure.SendMsgStateReq)
        SendMsgStateReqOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use SendMsgStateReq.newBuilder() to construct.
  private SendMsgStateReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SendMsgStateReq() {
    baseKey_ = com.google.protobuf.ByteString.EMPTY;
    identityKey_ = com.google.protobuf.ByteString.EMPTY;
    message_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
          UnusedPrivateParameter unused) {
    return new SendMsgStateReq();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SendMsgStateReq(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 16: {

            registrationId_ = input.readInt32();
            break;
          }
          case 24: {

            preKeyId_ = input.readInt32();
            break;
          }
          case 32: {

            signedPreKeyId_ = input.readInt32();
            break;
          }
          case 42: {

            baseKey_ = input.readBytes();
            break;
          }
          case 50: {

            identityKey_ = input.readBytes();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              message_ = new java.util.ArrayList<GroupPretypeMsgProtobuf.SentDistributionMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            message_.add(
                    input.readMessage(GroupPretypeMsgProtobuf.SentDistributionMessage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        message_ = java.util.Collections.unmodifiableList(message_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return GroupPretypeMsgProtobuf.internal_static_com_im_secure_SendMsgStateReq_descriptor;
  }

  @Override
  protected FieldAccessorTable
  internalGetFieldAccessorTable() {
    return GroupPretypeMsgProtobuf.internal_static_com_im_secure_SendMsgStateReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    GroupPretypeMsgProtobuf.SendMsgStateReq.class, GroupPretypeMsgProtobuf.SendMsgStateReq.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  public int getVersion() {
    return version_;
  }

  public static final int REGISTRATIONID_FIELD_NUMBER = 2;
  private int registrationId_;
  /**
   * <code>int32 registrationId = 2;</code>
   * @return The registrationId.
   */
  public int getRegistrationId() {
    return registrationId_;
  }

  public static final int PREKEYID_FIELD_NUMBER = 3;
  private int preKeyId_;
  /**
   * <code>int32 preKeyId = 3;</code>
   * @return The preKeyId.
   */
  public int getPreKeyId() {
    return preKeyId_;
  }

  public static final int SIGNEDPREKEYID_FIELD_NUMBER = 4;
  private int signedPreKeyId_;
  /**
   * <code>int32 signedPreKeyId = 4;</code>
   * @return The signedPreKeyId.
   */
  public int getSignedPreKeyId() {
    return signedPreKeyId_;
  }

  public static final int BASEKEY_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString baseKey_;
  /**
   * <code>bytes baseKey = 5;</code>
   * @return The baseKey.
   */
  public com.google.protobuf.ByteString getBaseKey() {
    return baseKey_;
  }

  public static final int IDENTITYKEY_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString identityKey_;
  /**
   * <code>bytes identityKey = 6;</code>
   * @return The identityKey.
   */
  public com.google.protobuf.ByteString getIdentityKey() {
    return identityKey_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 7;
  private java.util.List<GroupPretypeMsgProtobuf.SentDistributionMessage> message_;
  /**
   * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
   */
  public java.util.List<GroupPretypeMsgProtobuf.SentDistributionMessage> getMessageList() {
    return message_;
  }
  /**
   * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
   */
  public java.util.List<? extends GroupPretypeMsgProtobuf.SentDistributionMessageOrBuilder>
  getMessageOrBuilderList() {
    return message_;
  }
  /**
   * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
   */
  public int getMessageCount() {
    return message_.size();
  }
  /**
   * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
   */
  public GroupPretypeMsgProtobuf.SentDistributionMessage getMessage(int index) {
    return message_.get(index);
  }
  /**
   * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
   */
  public GroupPretypeMsgProtobuf.SentDistributionMessageOrBuilder getMessageOrBuilder(
          int index) {
    return message_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    if (registrationId_ != 0) {
      output.writeInt32(2, registrationId_);
    }
    if (preKeyId_ != 0) {
      output.writeInt32(3, preKeyId_);
    }
    if (signedPreKeyId_ != 0) {
      output.writeInt32(4, signedPreKeyId_);
    }
    if (!baseKey_.isEmpty()) {
      output.writeBytes(5, baseKey_);
    }
    if (!identityKey_.isEmpty()) {
      output.writeBytes(6, identityKey_);
    }
    for (int i = 0; i < message_.size(); i++) {
      output.writeMessage(7, message_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(1, version_);
    }
    if (registrationId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(2, registrationId_);
    }
    if (preKeyId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(3, preKeyId_);
    }
    if (signedPreKeyId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(4, signedPreKeyId_);
    }
    if (!baseKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(5, baseKey_);
    }
    if (!identityKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(6, identityKey_);
    }
    for (int i = 0; i < message_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(7, message_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof GroupPretypeMsgProtobuf.SendMsgStateReq)) {
      return super.equals(obj);
    }
    GroupPretypeMsgProtobuf.SendMsgStateReq other = (GroupPretypeMsgProtobuf.SendMsgStateReq) obj;

    if (getVersion()
            != other.getVersion()) return false;
    if (getRegistrationId()
            != other.getRegistrationId()) return false;
    if (getPreKeyId()
            != other.getPreKeyId()) return false;
    if (getSignedPreKeyId()
            != other.getSignedPreKeyId()) return false;
    if (!getBaseKey()
            .equals(other.getBaseKey())) return false;
    if (!getIdentityKey()
            .equals(other.getIdentityKey())) return false;
    if (!getMessageList()
            .equals(other.getMessageList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + REGISTRATIONID_FIELD_NUMBER;
    hash = (53 * hash) + getRegistrationId();
    hash = (37 * hash) + PREKEYID_FIELD_NUMBER;
    hash = (53 * hash) + getPreKeyId();
    hash = (37 * hash) + SIGNEDPREKEYID_FIELD_NUMBER;
    hash = (53 * hash) + getSignedPreKeyId();
    hash = (37 * hash) + BASEKEY_FIELD_NUMBER;
    hash = (53 * hash) + getBaseKey().hashCode();
    hash = (37 * hash) + IDENTITYKEY_FIELD_NUMBER;
    hash = (53 * hash) + getIdentityKey().hashCode();
    if (getMessageCount() > 0) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GroupPretypeMsgProtobuf.SendMsgStateReq parseFrom(
          java.nio.ByteBuffer data)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GroupPretypeMsgProtobuf.SendMsgStateReq parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.SendMsgStateReq parseFrom(
          com.google.protobuf.ByteString data)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GroupPretypeMsgProtobuf.SendMsgStateReq parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.SendMsgStateReq parseFrom(byte[] data)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GroupPretypeMsgProtobuf.SendMsgStateReq parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.SendMsgStateReq parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }
  public static GroupPretypeMsgProtobuf.SendMsgStateReq parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.SendMsgStateReq parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }
  public static GroupPretypeMsgProtobuf.SendMsgStateReq parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.SendMsgStateReq parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }
  public static GroupPretypeMsgProtobuf.SendMsgStateReq parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GroupPretypeMsgProtobuf.SendMsgStateReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
          BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.im.secure.SendMsgStateReq}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.im.secure.SendMsgStateReq)
          GroupPretypeMsgProtobuf.SendMsgStateReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return GroupPretypeMsgProtobuf.internal_static_com_im_secure_SendMsgStateReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return GroupPretypeMsgProtobuf.internal_static_com_im_secure_SendMsgStateReq_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      GroupPretypeMsgProtobuf.SendMsgStateReq.class, GroupPretypeMsgProtobuf.SendMsgStateReq.Builder.class);
    }

    // Construct using com.im.secure.GroupPretypeMsgProtobuf.SendMsgStateReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMessageFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      registrationId_ = 0;

      preKeyId_ = 0;

      signedPreKeyId_ = 0;

      baseKey_ = com.google.protobuf.ByteString.EMPTY;

      identityKey_ = com.google.protobuf.ByteString.EMPTY;

      if (messageBuilder_ == null) {
        message_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        messageBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return GroupPretypeMsgProtobuf.internal_static_com_im_secure_SendMsgStateReq_descriptor;
    }

    @Override
    public GroupPretypeMsgProtobuf.SendMsgStateReq getDefaultInstanceForType() {
      return GroupPretypeMsgProtobuf.SendMsgStateReq.getDefaultInstance();
    }

    @Override
    public GroupPretypeMsgProtobuf.SendMsgStateReq build() {
      GroupPretypeMsgProtobuf.SendMsgStateReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GroupPretypeMsgProtobuf.SendMsgStateReq buildPartial() {
      GroupPretypeMsgProtobuf.SendMsgStateReq result = new GroupPretypeMsgProtobuf.SendMsgStateReq(this);
      int from_bitField0_ = bitField0_;
      result.version_ = version_;
      result.registrationId_ = registrationId_;
      result.preKeyId_ = preKeyId_;
      result.signedPreKeyId_ = signedPreKeyId_;
      result.baseKey_ = baseKey_;
      result.identityKey_ = identityKey_;
      if (messageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          message_ = java.util.Collections.unmodifiableList(message_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.message_ = message_;
      } else {
        result.message_ = messageBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GroupPretypeMsgProtobuf.SendMsgStateReq) {
        return mergeFrom((GroupPretypeMsgProtobuf.SendMsgStateReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GroupPretypeMsgProtobuf.SendMsgStateReq other) {
      if (other == GroupPretypeMsgProtobuf.SendMsgStateReq.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getRegistrationId() != 0) {
        setRegistrationId(other.getRegistrationId());
      }
      if (other.getPreKeyId() != 0) {
        setPreKeyId(other.getPreKeyId());
      }
      if (other.getSignedPreKeyId() != 0) {
        setSignedPreKeyId(other.getSignedPreKeyId());
      }
      if (other.getBaseKey() != com.google.protobuf.ByteString.EMPTY) {
        setBaseKey(other.getBaseKey());
      }
      if (other.getIdentityKey() != com.google.protobuf.ByteString.EMPTY) {
        setIdentityKey(other.getIdentityKey());
      }
      if (messageBuilder_ == null) {
        if (!other.message_.isEmpty()) {
          if (message_.isEmpty()) {
            message_ = other.message_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMessageIsMutable();
            message_.addAll(other.message_);
          }
          onChanged();
        }
      } else {
        if (!other.message_.isEmpty()) {
          if (messageBuilder_.isEmpty()) {
            messageBuilder_.dispose();
            messageBuilder_ = null;
            message_ = other.message_;
            bitField0_ = (bitField0_ & ~0x00000001);
            messageBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getMessageFieldBuilder() : null;
          } else {
            messageBuilder_.addAllMessages(other.message_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      GroupPretypeMsgProtobuf.SendMsgStateReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (InvalidProtocolBufferException e) {
        parsedMessage = (GroupPretypeMsgProtobuf.SendMsgStateReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {

      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {

      version_ = 0;
      onChanged();
      return this;
    }

    private int registrationId_ ;
    /**
     * <code>int32 registrationId = 2;</code>
     * @return The registrationId.
     */
    public int getRegistrationId() {
      return registrationId_;
    }
    /**
     * <code>int32 registrationId = 2;</code>
     * @param value The registrationId to set.
     * @return This builder for chaining.
     */
    public Builder setRegistrationId(int value) {

      registrationId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 registrationId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegistrationId() {

      registrationId_ = 0;
      onChanged();
      return this;
    }

    private int preKeyId_ ;
    /**
     * <code>int32 preKeyId = 3;</code>
     * @return The preKeyId.
     */
    public int getPreKeyId() {
      return preKeyId_;
    }
    /**
     * <code>int32 preKeyId = 3;</code>
     * @param value The preKeyId to set.
     * @return This builder for chaining.
     */
    public Builder setPreKeyId(int value) {

      preKeyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 preKeyId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreKeyId() {

      preKeyId_ = 0;
      onChanged();
      return this;
    }

    private int signedPreKeyId_ ;
    /**
     * <code>int32 signedPreKeyId = 4;</code>
     * @return The signedPreKeyId.
     */
    public int getSignedPreKeyId() {
      return signedPreKeyId_;
    }
    /**
     * <code>int32 signedPreKeyId = 4;</code>
     * @param value The signedPreKeyId to set.
     * @return This builder for chaining.
     */
    public Builder setSignedPreKeyId(int value) {

      signedPreKeyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 signedPreKeyId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignedPreKeyId() {

      signedPreKeyId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString baseKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes baseKey = 5;</code>
     * @return The baseKey.
     */
    public com.google.protobuf.ByteString getBaseKey() {
      return baseKey_;
    }
    /**
     * <code>bytes baseKey = 5;</code>
     * @param value The baseKey to set.
     * @return This builder for chaining.
     */
    public Builder setBaseKey(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }

      baseKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes baseKey = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBaseKey() {

      baseKey_ = getDefaultInstance().getBaseKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString identityKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes identityKey = 6;</code>
     * @return The identityKey.
     */
    public com.google.protobuf.ByteString getIdentityKey() {
      return identityKey_;
    }
    /**
     * <code>bytes identityKey = 6;</code>
     * @param value The identityKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdentityKey(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }

      identityKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes identityKey = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdentityKey() {

      identityKey_ = getDefaultInstance().getIdentityKey();
      onChanged();
      return this;
    }

    private java.util.List<GroupPretypeMsgProtobuf.SentDistributionMessage> message_ =
            java.util.Collections.emptyList();
    private void ensureMessageIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        message_ = new java.util.ArrayList<GroupPretypeMsgProtobuf.SentDistributionMessage>(message_);
        bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            GroupPretypeMsgProtobuf.SentDistributionMessage, GroupPretypeMsgProtobuf.SentDistributionMessage.Builder, GroupPretypeMsgProtobuf.SentDistributionMessageOrBuilder> messageBuilder_;

    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public java.util.List<GroupPretypeMsgProtobuf.SentDistributionMessage> getMessageList() {
      if (messageBuilder_ == null) {
        return java.util.Collections.unmodifiableList(message_);
      } else {
        return messageBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public int getMessageCount() {
      if (messageBuilder_ == null) {
        return message_.size();
      } else {
        return messageBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public GroupPretypeMsgProtobuf.SentDistributionMessage getMessage(int index) {
      if (messageBuilder_ == null) {
        return message_.get(index);
      } else {
        return messageBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public Builder setMessage(
            int index, GroupPretypeMsgProtobuf.SentDistributionMessage value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageIsMutable();
        message_.set(index, value);
        onChanged();
      } else {
        messageBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public Builder setMessage(
            int index, GroupPretypeMsgProtobuf.SentDistributionMessage.Builder builderForValue) {
      if (messageBuilder_ == null) {
        ensureMessageIsMutable();
        message_.set(index, builderForValue.build());
        onChanged();
      } else {
        messageBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public Builder addMessage(GroupPretypeMsgProtobuf.SentDistributionMessage value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageIsMutable();
        message_.add(value);
        onChanged();
      } else {
        messageBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public Builder addMessage(
            int index, GroupPretypeMsgProtobuf.SentDistributionMessage value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageIsMutable();
        message_.add(index, value);
        onChanged();
      } else {
        messageBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public Builder addMessage(
            GroupPretypeMsgProtobuf.SentDistributionMessage.Builder builderForValue) {
      if (messageBuilder_ == null) {
        ensureMessageIsMutable();
        message_.add(builderForValue.build());
        onChanged();
      } else {
        messageBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public Builder addMessage(
            int index, GroupPretypeMsgProtobuf.SentDistributionMessage.Builder builderForValue) {
      if (messageBuilder_ == null) {
        ensureMessageIsMutable();
        message_.add(index, builderForValue.build());
        onChanged();
      } else {
        messageBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public Builder addAllMessage(
            Iterable<? extends GroupPretypeMsgProtobuf.SentDistributionMessage> values) {
      if (messageBuilder_ == null) {
        ensureMessageIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, message_);
        onChanged();
      } else {
        messageBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public Builder clearMessage() {
      if (messageBuilder_ == null) {
        message_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        messageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public Builder removeMessage(int index) {
      if (messageBuilder_ == null) {
        ensureMessageIsMutable();
        message_.remove(index);
        onChanged();
      } else {
        messageBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public GroupPretypeMsgProtobuf.SentDistributionMessage.Builder getMessageBuilder(
            int index) {
      return getMessageFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public GroupPretypeMsgProtobuf.SentDistributionMessageOrBuilder getMessageOrBuilder(
            int index) {
      if (messageBuilder_ == null) {
        return message_.get(index);  } else {
        return messageBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public java.util.List<? extends GroupPretypeMsgProtobuf.SentDistributionMessageOrBuilder>
    getMessageOrBuilderList() {
      if (messageBuilder_ != null) {
        return messageBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(message_);
      }
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public GroupPretypeMsgProtobuf.SentDistributionMessage.Builder addMessageBuilder() {
      return getMessageFieldBuilder().addBuilder(
              GroupPretypeMsgProtobuf.SentDistributionMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public GroupPretypeMsgProtobuf.SentDistributionMessage.Builder addMessageBuilder(
            int index) {
      return getMessageFieldBuilder().addBuilder(
              index, GroupPretypeMsgProtobuf.SentDistributionMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.im.secure.SentDistributionMessage message = 7;</code>
     */
    public java.util.List<GroupPretypeMsgProtobuf.SentDistributionMessage.Builder>
    getMessageBuilderList() {
      return getMessageFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            GroupPretypeMsgProtobuf.SentDistributionMessage, GroupPretypeMsgProtobuf.SentDistributionMessage.Builder, GroupPretypeMsgProtobuf.SentDistributionMessageOrBuilder>
    getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        messageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                GroupPretypeMsgProtobuf.SentDistributionMessage, GroupPretypeMsgProtobuf.SentDistributionMessage.Builder, GroupPretypeMsgProtobuf.SentDistributionMessageOrBuilder>(
                message_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      return messageBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.im.secure.SendMsgStateReq)
  }

  // @@protoc_insertion_point(class_scope:com.im.secure.SendMsgStateReq)
  private static final GroupPretypeMsgProtobuf.SendMsgStateReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GroupPretypeMsgProtobuf.SendMsgStateReq();
  }

  public static GroupPretypeMsgProtobuf.SendMsgStateReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendMsgStateReq>
          PARSER = new com.google.protobuf.AbstractParser<SendMsgStateReq>() {
    @Override
    public SendMsgStateReq parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
      return new SendMsgStateReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SendMsgStateReq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SendMsgStateReq> getParserForType() {
    return PARSER;
  }

  @Override
  public GroupPretypeMsgProtobuf.SendMsgStateReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

public interface GroupSenderKeyDistributionMessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.im.secure.GroupSenderKeyDistributionMessage)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 iteration = 2;</code>
   * @return The iteration.
   */
  int getIteration();

  /**
   * <code>bytes chainKey = 3;</code>
   * @return The chainKey.
   */
  com.google.protobuf.ByteString getChainKey();

  /**
   * <code>bytes signatureKey = 4;</code>
   * @return The signatureKey.
   */
  com.google.protobuf.ByteString getSignatureKey();

  /**
   * <code>bytes privateKey = 5;</code>
   * @return The privateKey.
   */
  com.google.protobuf.ByteString getPrivateKey();
}
/**
 * Protobuf type {@code com.im.secure.GroupSenderKeyDistributionMessage}
 */
public  static final class GroupSenderKeyDistributionMessage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.im.secure.GroupSenderKeyDistributionMessage)
        GroupSenderKeyDistributionMessageOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use GroupSenderKeyDistributionMessage.newBuilder() to construct.
  private GroupSenderKeyDistributionMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GroupSenderKeyDistributionMessage() {
    chainKey_ = com.google.protobuf.ByteString.EMPTY;
    signatureKey_ = com.google.protobuf.ByteString.EMPTY;
    privateKey_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
          UnusedPrivateParameter unused) {
    return new GroupSenderKeyDistributionMessage();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GroupSenderKeyDistributionMessage(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 16: {

            iteration_ = input.readInt32();
            break;
          }
          case 26: {

            chainKey_ = input.readBytes();
            break;
          }
          case 34: {

            signatureKey_ = input.readBytes();
            break;
          }
          case 42: {

            privateKey_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return GroupPretypeMsgProtobuf.internal_static_com_im_secure_GroupSenderKeyDistributionMessage_descriptor;
  }

  @Override
  protected FieldAccessorTable
  internalGetFieldAccessorTable() {
    return GroupPretypeMsgProtobuf.internal_static_com_im_secure_GroupSenderKeyDistributionMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage.class, GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  public int getId() {
    return id_;
  }

  public static final int ITERATION_FIELD_NUMBER = 2;
  private int iteration_;
  /**
   * <code>int32 iteration = 2;</code>
   * @return The iteration.
   */
  public int getIteration() {
    return iteration_;
  }

  public static final int CHAINKEY_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString chainKey_;
  /**
   * <code>bytes chainKey = 3;</code>
   * @return The chainKey.
   */
  public com.google.protobuf.ByteString getChainKey() {
    return chainKey_;
  }

  public static final int SIGNATUREKEY_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString signatureKey_;
  /**
   * <code>bytes signatureKey = 4;</code>
   * @return The signatureKey.
   */
  public com.google.protobuf.ByteString getSignatureKey() {
    return signatureKey_;
  }

  public static final int PRIVATEKEY_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString privateKey_;
  /**
   * <code>bytes privateKey = 5;</code>
   * @return The privateKey.
   */
  public com.google.protobuf.ByteString getPrivateKey() {
    return privateKey_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (iteration_ != 0) {
      output.writeInt32(2, iteration_);
    }
    if (!chainKey_.isEmpty()) {
      output.writeBytes(3, chainKey_);
    }
    if (!signatureKey_.isEmpty()) {
      output.writeBytes(4, signatureKey_);
    }
    if (!privateKey_.isEmpty()) {
      output.writeBytes(5, privateKey_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(1, id_);
    }
    if (iteration_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(2, iteration_);
    }
    if (!chainKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(3, chainKey_);
    }
    if (!signatureKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(4, signatureKey_);
    }
    if (!privateKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(5, privateKey_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage)) {
      return super.equals(obj);
    }
    GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage other = (GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage) obj;

    if (getId()
            != other.getId()) return false;
    if (getIteration()
            != other.getIteration()) return false;
    if (!getChainKey()
            .equals(other.getChainKey())) return false;
    if (!getSignatureKey()
            .equals(other.getSignatureKey())) return false;
    if (!getPrivateKey()
            .equals(other.getPrivateKey())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + ITERATION_FIELD_NUMBER;
    hash = (53 * hash) + getIteration();
    hash = (37 * hash) + CHAINKEY_FIELD_NUMBER;
    hash = (53 * hash) + getChainKey().hashCode();
    hash = (37 * hash) + SIGNATUREKEY_FIELD_NUMBER;
    hash = (53 * hash) + getSignatureKey().hashCode();
    hash = (37 * hash) + PRIVATEKEY_FIELD_NUMBER;
    hash = (53 * hash) + getPrivateKey().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage parseFrom(
          java.nio.ByteBuffer data)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage parseFrom(
          com.google.protobuf.ByteString data)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage parseFrom(byte[] data)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }
  public static GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }
  public static GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }
  public static GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
          BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.im.secure.GroupSenderKeyDistributionMessage}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.im.secure.GroupSenderKeyDistributionMessage)
          GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return GroupPretypeMsgProtobuf.internal_static_com_im_secure_GroupSenderKeyDistributionMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return GroupPretypeMsgProtobuf.internal_static_com_im_secure_GroupSenderKeyDistributionMessage_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage.class, GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage.Builder.class);
    }

    // Construct using com.im.secure.GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      iteration_ = 0;

      chainKey_ = com.google.protobuf.ByteString.EMPTY;

      signatureKey_ = com.google.protobuf.ByteString.EMPTY;

      privateKey_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return GroupPretypeMsgProtobuf.internal_static_com_im_secure_GroupSenderKeyDistributionMessage_descriptor;
    }

    @Override
    public GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage getDefaultInstanceForType() {
      return GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage.getDefaultInstance();
    }

    @Override
    public GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage build() {
      GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage buildPartial() {
      GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage result = new GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage(this);
      result.id_ = id_;
      result.iteration_ = iteration_;
      result.chainKey_ = chainKey_;
      result.signatureKey_ = signatureKey_;
      result.privateKey_ = privateKey_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage) {
        return mergeFrom((GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage other) {
      if (other == GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getIteration() != 0) {
        setIteration(other.getIteration());
      }
      if (other.getChainKey() != com.google.protobuf.ByteString.EMPTY) {
        setChainKey(other.getChainKey());
      }
      if (other.getSignatureKey() != com.google.protobuf.ByteString.EMPTY) {
        setSignatureKey(other.getSignatureKey());
      }
      if (other.getPrivateKey() != com.google.protobuf.ByteString.EMPTY) {
        setPrivateKey(other.getPrivateKey());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (InvalidProtocolBufferException e) {
        parsedMessage = (GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {

      id_ = 0;
      onChanged();
      return this;
    }

    private int iteration_ ;
    /**
     * <code>int32 iteration = 2;</code>
     * @return The iteration.
     */
    public int getIteration() {
      return iteration_;
    }
    /**
     * <code>int32 iteration = 2;</code>
     * @param value The iteration to set.
     * @return This builder for chaining.
     */
    public Builder setIteration(int value) {

      iteration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 iteration = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIteration() {

      iteration_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString chainKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes chainKey = 3;</code>
     * @return The chainKey.
     */
    public com.google.protobuf.ByteString getChainKey() {
      return chainKey_;
    }
    /**
     * <code>bytes chainKey = 3;</code>
     * @param value The chainKey to set.
     * @return This builder for chaining.
     */
    public Builder setChainKey(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }

      chainKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes chainKey = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearChainKey() {

      chainKey_ = getDefaultInstance().getChainKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString signatureKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes signatureKey = 4;</code>
     * @return The signatureKey.
     */
    public com.google.protobuf.ByteString getSignatureKey() {
      return signatureKey_;
    }
    /**
     * <code>bytes signatureKey = 4;</code>
     * @param value The signatureKey to set.
     * @return This builder for chaining.
     */
    public Builder setSignatureKey(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }

      signatureKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes signatureKey = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignatureKey() {

      signatureKey_ = getDefaultInstance().getSignatureKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString privateKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes privateKey = 5;</code>
     * @return The privateKey.
     */
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }
    /**
     * <code>bytes privateKey = 5;</code>
     * @param value The privateKey to set.
     * @return This builder for chaining.
     */
    public Builder setPrivateKey(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }

      privateKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes privateKey = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrivateKey() {

      privateKey_ = getDefaultInstance().getPrivateKey();
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.im.secure.GroupSenderKeyDistributionMessage)
  }

  // @@protoc_insertion_point(class_scope:com.im.secure.GroupSenderKeyDistributionMessage)
  private static final GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage();
  }

  public static GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GroupSenderKeyDistributionMessage>
          PARSER = new com.google.protobuf.AbstractParser<GroupSenderKeyDistributionMessage>() {
    @Override
    public GroupSenderKeyDistributionMessage parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
      return new GroupSenderKeyDistributionMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GroupSenderKeyDistributionMessage> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GroupSenderKeyDistributionMessage> getParserForType() {
    return PARSER;
  }

  @Override
  public GroupPretypeMsgProtobuf.GroupSenderKeyDistributionMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_com_im_secure_SentDistributionMessage_descriptor;
private static final
com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_com_im_secure_SentDistributionMessage_fieldAccessorTable;
private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_com_im_secure_SendMsgStateReq_descriptor;
private static final
com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_com_im_secure_SendMsgStateReq_fieldAccessorTable;
private static final com.google.protobuf.Descriptors.Descriptor
        internal_static_com_im_secure_GroupSenderKeyDistributionMessage_descriptor;
private static final
com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_com_im_secure_GroupSenderKeyDistributionMessage_fieldAccessorTable;

public static com.google.protobuf.Descriptors.FileDescriptor
getDescriptor() {
  return descriptor;
}
private static  com.google.protobuf.Descriptors.FileDescriptor
        descriptor;
static {
  String[] descriptorData = {
          "\n\025GroupPretypeMsg.proto\022\rcom.im.secure\"y" +
                  "\n\027SentDistributionMessage\022\017\n\007version\030\001 \001" +
                  "(\005\022\016\n\006userId\030\002 \001(\003\022\025\n\ridentityKeyId\030\003 \001(" +
                  "\005\022\026\n\016signedPreKeyId\030\004 \001(\005\022\016\n\006oneMsg\030\005 \001(" +
                  "\014\"\303\001\n\017SendMsgStateReq\022\017\n\007version\030\001 \001(\005\022\026" +
                  "\n\016registrationId\030\002 \001(\005\022\020\n\010preKeyId\030\003 \001(\005" +
                  "\022\026\n\016signedPreKeyId\030\004 \001(\005\022\017\n\007baseKey\030\005 \001(" +
                  "\014\022\023\n\013identityKey\030\006 \001(\014\0227\n\007message\030\007 \003(\0132" +
                  "&.com.im.secure.SentDistributionMessage\"" +
                  "~\n!GroupSenderKeyDistributionMessage\022\n\n\002" +
                  "id\030\001 \001(\005\022\021\n\titeration\030\002 \001(\005\022\020\n\010chainKey\030" +
                  "\003 \001(\014\022\024\n\014signatureKey\030\004 \001(\014\022\022\n\nprivateKe" +
                  "y\030\005 \001(\014B(\n\rcom.im.secureB\027GroupPretypeMs" +
                  "gProtobufb\006proto3"
  };
  descriptor = com.google.protobuf.Descriptors.FileDescriptor
          .internalBuildGeneratedFileFrom(descriptorData,
                  new com.google.protobuf.Descriptors.FileDescriptor[] {
                  });
  internal_static_com_im_secure_SentDistributionMessage_descriptor =
          getDescriptor().getMessageTypes().get(0);
  internal_static_com_im_secure_SentDistributionMessage_fieldAccessorTable = new
          com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
          internal_static_com_im_secure_SentDistributionMessage_descriptor,
          new String[] { "Version", "UserId", "IdentityKeyId", "SignedPreKeyId", "OneMsg", });
  internal_static_com_im_secure_SendMsgStateReq_descriptor =
          getDescriptor().getMessageTypes().get(1);
  internal_static_com_im_secure_SendMsgStateReq_fieldAccessorTable = new
          com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
          internal_static_com_im_secure_SendMsgStateReq_descriptor,
          new String[] { "Version", "RegistrationId", "PreKeyId", "SignedPreKeyId", "BaseKey", "IdentityKey", "Message", });
  internal_static_com_im_secure_GroupSenderKeyDistributionMessage_descriptor =
          getDescriptor().getMessageTypes().get(2);
  internal_static_com_im_secure_GroupSenderKeyDistributionMessage_fieldAccessorTable = new
          com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
          internal_static_com_im_secure_GroupSenderKeyDistributionMessage_descriptor,
          new String[] { "Id", "Iteration", "ChainKey", "SignatureKey", "PrivateKey", });
}

// @@protoc_insertion_point(outer_class_scope)
}
